general:
  prefix: ms!

tokens:
  dev:
  prod:

sentry:
  dsn:

logging:
  - sink: sys.stdout
    level: INFO
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | <fg #FFA500>{name}</fg #FFA500> <red>-</red> <level>{message}</level>"
    colorize: True