general:
  prefix: ms!
  token: !ENV "TOKEN"

metrics:
  port: 9991

  channel: 868102822665785375
  frequency: 60

sentry:
  dsn: !ENV "SENTRY_DSN"

logging:
  - sink: sys.stdout
    level: DEBUG
    format: "{level} | {name} - {message}"
    serialize: True
    backtrace: False
    diagnose: False