name: Build & Publish

on:
  push:
    branches:
      - master

jobs:
  getversion:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.3
        with:
          dev-branch: develop
          minor-identifier: "/feat(?:ure)?:/"
          major-identifier: "/(?:BREAKING CHANGE:)|(?:^[a-z]+!:)/"

  sentry:
    name: Create Sentry Release
    needs: getversion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Push the Release to Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bored-corp
          SENTRY_PROJECT: share-music
        with:
          environment: production
          version: share-music@${{ needs.getversion.outputs.version }}

  settag:
    name: Create Git Tag from Version
    needs: getversion
    runs-on: ubuntu-latest
    steps:
      - name: Create the Tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ needs.getversion.outputs.version }}",
              sha: context.sha
            })

  build:
    name: Build & Push
    needs: getversion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/tooboredtocode/share-music:latest
          cache-to: type=inline
          tags: |
            ghcr.io/tooboredtocode/share-music:latest
            ghcr.io/tooboredtocode/share-music:${{ needs.getversion.outputs.version }}
          build-args: |
            version=${{ needs.getversion.outputs.version }}